name: safe_cam_app
description: "안전한 카메라 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  image: ^4.5.3
  image_gallery_saver: ^2.0.3
  http: ^0.13.3

flutter:

  uses-material-design: true
